Catch error when statusupdate is failing
When an error occurs at getting the status like

mebridge/node_modules/homebridge-ewelink-max/index.js:365
    const status = channel && device.params.switches && device.params.switches[channel-1] ? device.params.switches[channel-1].switch : device.params.switch || "off";
                                                                                                                                                     ^
TypeError: Cannot read property 'switch' of undefined

I updated to catch the error otherwise complete homebridge setup fails to run